# IODS Week 2

*This weeks assignments included data wrangling and analysis!*

##Brief Description of Data

*The data in this table is student responses to questions regarding 3 types of learning apporaches (Deep,Surface, and Strategic). The dataset also includes personal characteristics like age, gender.*
*Students were asked several questions (scale 1-5) regarding each type of learning. The average of these responses is presented in the table.* 

###Summary of Results
*For this data set, 66% of respondents were female and 34% were male. Their ages ranged from 17-55 (mean 25.5) years old. Points ranged from 7-33 (mean 22.7) The average scale rating of "attitude"", "deep", "stra", and "surf" was 3.1, 3.6, 3.1, and 2.7 respectively*

*Code*
  
print(students2014)
summary(students2014)

###Regression Models

*Code*

library(ggplot2)
qplot(attitude, points, data = students2014) + geom_smooth(method = "lm")

##### fit a linear model

points_v_attitude <- lm(points ~ attitude, data = students2014)

#### print out a summary of the model

summary(points_v_attitude)

#### Interpretation
*There is a statistically significant positive correlation between attitude and points (p=4.13e-09).The multiple R-squared value was 0.1906. This means that the strength of the correlation was relatively weak.*

####Diagnostic Plots

my_model2 <- lm(points ~ attitude + stra, data = students2014)

par(mfrow = c(2,2))
plot(my_model2, which = c(1,2,5))

*These diagnostic plots test various aspects of the data such as normality, linearity, and the effect of outliers.*
*These data appear to be normally distributed with a few outliers that could be affecting the linear regression model.*


